### ISSUE TITLE
Failed to marshal success response: proto: Marshal called with nil

### ISSUE THREAD

**Issue by jrostand** [sky-uk/osprey#13]
I'm running Osprey in a Kubernetes 1.10.2 cluster talking to Dex 2.10.0 and I get `Failed to marshal success response: proto: Marshal called with nil` on the callback from Dex after successful LDAP bind.

I note that in [server/web/server.go](https://github.com/sky-uk/osprey/blob/master/server/web/server.go#L132-L135) there's a check for `nil` on the response, but it continues to attempt to marshal even if `response` is `nil`. Is this intended behavior? And if so, any ideas about what could be causing my error?

**Comment by jrostand** [comment]
Wound up being as simple as `skipApprovalScreen: true` not being set on my Dex config. Sorry for the spurious issue!

**Comment by totahuanocotl** [comment]
good to know you managed to solve the issue!
Thank you for reporting this though, I think we should still handle that scenario more gracefully, so a warning for the possible cause would be the least we could do.
