### ISSUE TITLE
User configuration erased after log in

### ISSUE THREAD

**Issue by alanmcdadeatsky** [sky-uk/osprey#17]
Before login

```
CURRENT   NAME                 CLUSTER              AUTHINFO             NAMESPACE
    
*         a               a.b.c     a.b.c     namespace
```
After login 

```CURRENT   NAME                 CLUSTER              AUTHINFO             NAMESPACE
*         a               a.b.c     a.b.c      
```
Any config for the contexts that have been logged in is erased. Other contexts are left intact.

Nothing more than an annoyance, but it would be nice if it did not do this.

*EDIT:* Redacted content by @totahuanocotl

**Comment by totahuanocotl** [comment]
Fixed in https://github.com/sky-uk/osprey/releases/tag/v1.3.0
