### ISSUE TITLE
Default value for apiServerCA flag?

### ISSUE THREAD

**Issue by nocquidant** [sky-uk/osprey#33]
I am not sure if the `--apiServerCA` flag is mandatory for osprey-server but if yes, wouldn't it be better to set the default to `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` which should work for most cases?

See https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod

Thanks
--nick

**Comment by mgreyo** [comment]
@nocquidant this was implemented as part of the v2.0 release.

Thanks for the suggestion!
