### ISSUE TITLE
failed to create oauth config still passes healthz

### ISSUE THREAD

**Issue by markdanko** [sky-uk/osprey#34]
failed to create oauth config: unable to create oidc provider "https://{FOO}:5556": Get https://{FOO}:5556/.well-known/openid-configuration: x509: certificate signed by unknown authority.

(that is kind of expected in a new cluster if starts before dex is ready, but I would like osprey to restart by itself in that case)
I would think this should exit on the "unable to create oidc provider" and/or change the healthz status to 500 unhealthly.

is that reasonable?

**Comment by totahuanocotl** [comment]
This has been released as [v1.5.0](https://github.com/sky-uk/osprey/releases/tag/v1.5.0)
