### ISSUE TITLE
Failed to parse dex response querying auth endpoint

### ISSUE THREAD

**Issue by gnasr** [sky-uk/osprey#40]
dex version 2.10.0 using ldap connector
osprey version 2.0
both running inside kube

When i try to log in, osprey server calls `consumeAuthResponse` which does a GET request to the dex endpoint
`/dex/auth?client_id=login&redirect_uri=https%3A%2F%2Flogin.example.com%2Fcallback%2Fauth&response_type=code&scope=groups+openid+profile+email+offline_access&....`

but dex response is an html with a login form instead of a json that consumeAuthResponse tries to marshal into a loginForm

```
type loginForm struct {
	Action        string `json:"action"`
	LoginField    string `json:"login"`
	LoginValue    string `json:"-"`
	PasswordField string `json:"password"`
	PasswordValue string `json:"-"`
	Invalid       bool   `json:"invalid,omitempty"`
}
```
the form:
![image](https://user-images.githubusercontent.com/3936970/65355214-cfa23600-dbc7-11e9-84ee-03ac9aed96a0.png)

and that obviously is traduced to a parsing error in osprey server
`failed to parse auth response: invalid character '<' looking for beginning of value`

do i have missconfigured dex or something?

thanks in advance

**Comment by totahuanocotl** [comment]
Hi @gnasr , 
If dex is returning an html response it might be because the templates it is using have not been overridden with the json ones ([here](https://github.com/sky-uk/osprey/blob/master/examples/kubernetes/dex/web-templates.yml) is an example of the templates, and [here](https://github.com/sky-uk/osprey/blob/master/examples/kubernetes/dex/dex.yml) is an example of the overriding).
Coul you confirm if you have done that?

**Comment by gnasr** [comment]
Yes that was the problem, i deployed dex manually and didn't notice that osprey requires those templates.
Thanks

**Comment by ekrasnoyarov** [comment]
> 



> Hi @gnasr , If dex is returning an html response it might be because the templates it is using have not been overridden with the json ones ([here](https://github.com/sky-uk/osprey/blob/master/examples/kubernetes/dex/web-templates.yml) is an example of the templates, and [here](https://github.com/sky-uk/osprey/blob/master/examples/kubernetes/dex/dex.yml) is an example of the overriding). Coul you confirm if you have done that?

Hi, i added as you whrote, now i got error
`failed to parse auth response: invalid character '}' looking for beginning of value`
