### ISSUE TITLE
404 error with kubernetes example deployment

### ISSUE THREAD

**Issue by nickperry** [sky-uk/osprey#5]
I am getting a "404 page not found" when doing an osprey user login against an osprey server set up with deploy-all.sh. 

The only things I have set in kubernetes.properties are node and context.

All that is in the logs is:

kubectl logs deploy/osprey-example-deployment -n osprey-example
time="2018-03-10T12:06:31Z" level=info msg="Starting to listen at: https://0.0.0.0:5555"

And for dex;

kubectl logs deploy/dex-example-deployment -n osprey-example
{"level":"info","msg":"config using log level: debug","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config issuer: https://10.20.20.11:31885","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config storage: sqlite3","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config static client: foo.cluster","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config connector: local passwords enabled","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config skipping approval screen","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config signing keys expire after: 24h0m0s","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"config id tokens valid for: 24h0m0s","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"keys expired, rotating","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"keys rotated, next rotation: 2018-03-11 12:06:13.944287479 +0000 UTC","time":"2018-03-10T12:06:13Z"}
{"level":"info","msg":"listening (https) on 0.0.0.0:5556","time":"2018-03-10T12:06:13Z"}
2018/03/10 12:10:14 http: TLS handshake error from 10.32.0.1:42790: remote error: tls: bad certificate

**Comment by totahuanocotl** [comment]
Hi @nickperry
I see you closed the issue, did you manage to get it working?

**Comment by nickperry** [comment]
Hi @totahuanocotl - sorry yes, I'm not sure what I did wrong. I re-deployed it and it's working great now. Thanks for all your work on this. The documentation and examples are really good.

**Comment by totahuanocotl** [comment]
Excellent! 
I am glad the examples are helpful, that was the aim!
