### ISSUE TITLE
Issue with the syntax apiServerUrl in README File

### ISSUE THREAD

**Issue by kevinsulatra** [sky-uk/osprey#50]

**Comment by kevinsulatra** [comment]
The syntax used for apiServerUrl is currently wrong in the README file line 384. 

https://github.com/sky-uk/osprey/blame/master/README.md#L384

`apiServerUrl` needs to be corrected to `apiServerURL` 

This causes an issue with the pod to display not ready and crash status when the config is applied to the kubernetes cluster.

**Comment by aecay** [comment]
Fixed by #51
