### ISSUE TITLE
https://dl.bintray.com/ Forbidden!

### ISSUE THREAD

**Issue by gkman** [sky-uk/osprey#62]
It seems like bintray.com service from JFrog has been shutdown and is now longer available for consumers to resolve dependencies.

**Comment by gdlx** [comment]
Is there an alternative place to download it ?

**Comment by adambro** [comment]
It looks that binaries hosting platform is being discontinued. From https://bintray.com/ announcement:
> Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th.
