### ISSUE TITLE
Create a binary distribution pipeline

### ISSUE THREAD

**Issue by aecay** [sky-uk/osprey#64]
Bintray, previously used to distribute open source binaries, has been discontinued (#62).  We need to create an alternative channel to release binaries to, which is publicly accessible.

Possible options:
- Github artifacts
- ...?

Requirements:
- Identify a binary host from the possible options above
- Upload the latest osprey version to those hosts
- Create tools to assist developers to upload future releases to that platform
- (optional) upload historic versions to the platform as well

**Comment by howardburgess** [comment]
Fixed in #72, creating binaries and checksums for all OSes and architectures when a new tag is pushed.

https://github.com/sky-uk/osprey/releases/tag/v2.6.0
