### ISSUE TITLE
Fix the SSL certificates in the tests

### ISSUE THREAD

**Issue by aecay** [sky-uk/osprey#65]
Currently the tests need the setting `GODEBUG=x509ignoreCN=0`.  That's because without that, on newer versions of go, the tests give the following error:

```
Post \"https://localhost:12984/access-token\": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

So ideally, the test suite needs to be updated so that it provisions certs that work with the expectations of the new versions of go (using SAN instead of CN, presumably).  Then we can remove the GODEBUG workaround from the makefile.

**Comment by ModelNaoe** [comment]
tough
