### ISSUE TITLE
Add target groups in client config

### ISSUE THREAD

**Issue by lw346** [sky-uk/osprey#9]
Allow users to configure group targets in the ospreyconfig, and to specify a group target when logging in. 
The user should be able to specify a default group. 

- If a group is provided, osprey should only login to the targets in that group. 
  - If the group does not exist, it should display an error.
- if a group is not provided
  - if no default group is configured, opsrey should login to any targets not belonging to a group. 
  - if a default group is configured, osprey should only login to the targets in the default group. 

- If there are no targets in a group, or outside a group for any of the scenarios before osprey should do nothing.

**Comment by totahuanocotl** [comment]
Released in https://github.com/sky-uk/osprey/releases/tag/v1.3.0
